make numerical-recipes:
	mkdir -p out
	g++ numerical-recipes.cpp -o out/numerical-recipes -O2 -std=c++17
	out/numerical-recipes

make zx81:
	mkdir -p out
	g++ zx81.cpp -o out/zx81 -O2 -std=c++17
	out/zx81
